{
	"version": 1712586080,
	"fileList": [
		"data.js",
		"c2runtime.js",
		"jquery-3.4.1.min.js",
		"offlineClient.js",
		"images/cards-sheet0.png",
		"images/bgcheckered-sheet0.png",
		"images/levelpanel-sheet0.png",
		"images/backbutton-sheet0.png",
		"images/spritefont.png",
		"images/levelselect-sheet0.png",
		"images/levelavailable-sheet0.png",
		"images/levelavailable-sheet1.png",
		"images/numbers-sheet0.png",
		"images/title-sheet0.png",
		"images/playbutton-sheet0.png",
		"images/titlename-sheet0.png",
		"images/background.png",
		"images/levelcleared-sheet0.png",
		"images/replaylevel-sheet0.png",
		"images/levelselectionbtn-sheet0.png",
		"images/nextlevel-sheet0.png",
		"images/sfpoints.png",
		"images/shadow-sheet0.png",
		"images/soundfxsheet-sheet0.png",
		"images/soundfxsheet-sheet1.png",
		"images/mwlogo-sheet0.png",
		"images/cardbg-sheet0.png",
		"images/card-sheet0.png",
		"images/card2-sheet0.png",
		"images/card3-sheet0.png",
		"images/card4-sheet0.png",
		"images/card5-sheet0.png",
		"images/name.png",
		"images/lside-sheet0.png",
		"images/rside-sheet0.png",
		"images/rside2-sheet0.png",
		"images/lside2-sheet0.png",
		"images/txt-sheet0.png",
		"images/sprite-sheet0.png",
		"images/sprite2-sheet0.png",
		"images/sprite3-sheet0.png",
		"images/sprite4-sheet0.png",
		"images/congrats-sheet0.png",
		"images/congratstitle-sheet0.png",
		"images/openbtn-sheet0.png",
		"images/art-sheet0.png",
		"images/fg-sheet0.png",
		"images/glarelight-sheet0.png",
		"images/ooredoo-sheet0.png",
		"images/ooredoo2-sheet0.png",
		"images/ooredoo3-sheet0.png",
		"media/life_of_riley.m4a",
		"media/life_of_riley.ogg",
		"media/levelclear.m4a",
		"media/levelclear.ogg",
		"media/in the ramadan.m4a",
		"media/in the ramadan.ogg",
		"media/openeffect.ogg",
		"media/openeffect.m4a",
		"media/raspberrymusic - the ramadan.ogg",
		"media/raspberrymusic - the ramadan.m4a",
		"media/deepwoken talent card flip sound effect.ogg",
		"media/deepwoken talent card flip sound effect.m4a",
		"icon-16.png",
		"icon-32.png",
		"icon-114.png",
		"icon-128.png",
		"icon-256.png",
		"loading-logo.png"
	]
}